# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/larry/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),larry)

$(call add-radio-file-sha1-checked,radio/abl.img,0c0196bbbbee815e16c2260545a669e1e68290ac)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,b9cd495b39a1567eb8f1bb39b34ceddeba1a05ae)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,632bdf37664253763fd18a4f8127084bcb20f7f8)
$(call add-radio-file-sha1-checked,radio/devcfg.img,a61ae76eaf4412feec366506240c88b36393ecf8)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,41fd40d26182a207a93772ff11ca52196ac2736f)
$(call add-radio-file-sha1-checked,radio/hyp.img,4b0324730c5cf4dad7ea0f166e7077372cc963bc)
$(call add-radio-file-sha1-checked,radio/imagefv.img,7b3d3baed50fd691afe674b29f726453a0cf49a3)
$(call add-radio-file-sha1-checked,radio/keymaster.img,79af53d53589449ff92d73f950842cce514a99e3)
$(call add-radio-file-sha1-checked,radio/modem.img,442992ad49b9e27c74c57441e016503a476b5022)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,bb4c1845882dd67e42aa0816ad061b877c9dbd90)
$(call add-radio-file-sha1-checked,radio/qupfw.img,a1a5decf957bd687e979c44add117cb74cfe1097)
$(call add-radio-file-sha1-checked,radio/rpm.img,8f1c049f28be883f2b8264bd387b810ef3f999e7)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,9dfa57d0a97187276e5607fc23bf20e7bd2bc9d2)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,d28839351851a07f8e2fa955e112ea6b3fb55234)
$(call add-radio-file-sha1-checked,radio/xbl.img,f47207e33ff8a69ea87813e8cc33463716c28ff4)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,b1d017d1e425d53eec7c81b117c68f7749a09c6f)

endif
