# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/larry/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),larry)

$(call add-radio-file-sha1-checked,radio/abl.img,cebf4c1b79b8bb8d375e851c30a48a860a34d027)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,69af34d569499188d397174ecdeda449c4df438f)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,934d8f51f738e62fff4be8083c8883fa0d9ea326)
$(call add-radio-file-sha1-checked,radio/devcfg.img,49a17ad7e9d922fac4ada86578a477dc08de6c0b)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,312c42a9dd7de74c1d8e4e3f793c72a7f7b37fe7)
$(call add-radio-file-sha1-checked,radio/hyp.img,aa2773019816b4af9728dcc4f43dfafe20517765)
$(call add-radio-file-sha1-checked,radio/imagefv.img,2f045c685b252db53a5328f9eeafd723734007f9)
$(call add-radio-file-sha1-checked,radio/keymaster.img,ceb57d66f15a481e46d0e2a03fd3b7d1cda115f6)
$(call add-radio-file-sha1-checked,radio/modem.img,339973613ae3fd641f9fbb97688007cbdbb35e89)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,5511a32ba92cdbf884c6173be362228fe9589d3c)
$(call add-radio-file-sha1-checked,radio/qupfw.img,f849ce2631aaf97b20256a7c3e9d5633853b7e45)
$(call add-radio-file-sha1-checked,radio/rpm.img,4600623ac10428a9866846eeeb24588810ab11b3)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,a80bf2e7ac0e4d3ec0cf1cd8462ede16fd056c09)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,580f6567b7b15b9913e3b821cfc629a262b0829c)
$(call add-radio-file-sha1-checked,radio/xbl.img,bed846128c4c336d5349e0446347ccae31afc491)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,33916d0a243f80f4b285c0d60185322f52e07d83)

endif
